version: 2

sphinx:
  configuration: doc/conf.py

formats: 
  - htmlzip
  - epub

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
